RES_URL = 'game/res/'
GAME_DIM = 1000
WALL_THICKNESS = 10
ACC = 25
DEFAULT_BB_OFFSET_X_SCALE = 0.25
DEFAULT_BB_OFFSET_Y_SCALE = 0.5
MAX_ROBOT_SPEED = 300 # in units/s
GOAL_RADIUS = 50 # px, obviously
JUNCTION_RADIUS = 10
DEBUG = True # renders bounding boxes, vectors, etc.
FORCE_SCALING_FACTOR = 100 # scales forces so they have a sensible magnitude